server:
  port: 8080
  
spring:
  application:
    name: springboot-mybatis
    
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-mybatis
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
  - classpath*:mappers/**/*Mapper.xml


logging:
  level:
    sample: debug  