server:
  port: 9004
  
spring:
  application:
    name: business-consumer-ribbon-hystrix
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
      
provider:
  url: http://business-provider