server:
  port: 9005
  
spring:
  application:
    name: business-consumer-feign-hystrix
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
      
feign:
  hystrix:
    enabled: true